#!/usr/bin/env python
import sys


# fetch arguments
def fetch(arguments,index):
	try:
		res = arguments[index]
	except IndexError:
		res = 0
	return res





# put in your girl's name here
my_love = "put-in-name-here"

# fetch argument list and convert to lower case
arguments =[item.lower() for item in sys.argv[1:]]
if fetch(arguments, 0) == "love":
    if fetch(arguments, 1) == my_love:
        print "I know you do, sweety"
    else:
        print "No ! You love "+ my_love.capitalize()
else:
    print "C'mon, talk about love! Cause love is in the air <3 "